lane_detection_node:
  ros__parameters:
    Hue_low : 18
    Hue_high : 50
    Saturation_low : 75
    Saturation_high : 255
    Value_low : 145
    Value_high : 255
    number_of_lines : 100
    error_threshold : 0.16
    Width_min : 15
    Width_max : 112
    gray_lower : 61
    inverted_filter : 0
    kernal_size : 3
    erosion_itterations : 1
    dilation_itterations : 4
    crop_width_decimal : 0.7
    rows_to_watch_decimal : 0.2
    rows_offset_decimal : 0.5
    camera_centerline : 0.55

calibration_node:
  ros__parameters:
    Hue_low : 18
    Hue_high : 50
    Saturation_low : 75
    Saturation_high : 255
    Value_low : 145
    Value_high : 255
    number_of_lines : 100
    error_threshold : 0.16
    Width_min : 15
    Width_max : 112
    gray_lower : 61
    inverted_filter : 0
    kernal_size : 3
    erosion_itterations : 1
    dilation_itterations : 4
    crop_width_decimal : 0.7
    rows_to_watch_decimal : 0.2
    rows_offset_decimal : 0.5
    camera_centerline : 0.55

lane_guidance_node:
  ros__parameters:
    # Basic PID steering control parameters
    Kp_steering : 0.2              # Proportional gain for steering [0,1]
    Ki_steering : 0.0              # Integral gain for steering [0,1] 
    Kd_steering : 0.1              # Derivative gain for steering [0,1]
    error_threshold : 0.15         # Error threshold for control [0,1]
    
    # Throttle/speed control parameters
    zero_throttle : 0.0            # Zero throttle value [-1,1], should be around 0
    max_throttle : 0.2             # Maximum throttle value [-1,1]
    min_throttle : 0.1             # Minimum throttle value [-1,1]
    
    # Steering limits
    max_right_steering : 1.0       # Maximum right steering value [-1,1]
    max_left_steering : -1.0       # Maximum left steering value [-1,1]
    
    # Obstacle detection parameters
    depth_threshold : 0.2          # Distance threshold for obstacle detection (meters)
    roi_width_ratio : 0.3          # Width of center ROI as ratio of image width [0,1]
    roi_height_ratio : 0.5         # Height of center ROI as ratio of image height [0,1]
    
    # Servo sweep parameters for obstacle scanning
    sweep_duration : 5.0           # Duration to run servo sweeper (seconds)
    resume_delay : 1.2             # Wait time after sweep before resuming (seconds)
    
    # Avoidance maneuver motion parameters
    turn_speed : 0.5               # Angular velocity for turns (rad/s)
    forward_speed : 0.15           # Linear velocity for forward movement (m/s)
    reverse_speed : -0.15          # Linear velocity for reverse movement (m/s)
    turn_angle_deg : 80.0          # Turn angle for avoidance maneuver (degrees)
    forward_distance : 0.4         # Forward distance during avoidance (meters)
    reverse_distance : 0.4         # Reverse distance during avoidance (meters)
    final_forward_distance : 0.34  # Final forward distance to complete avoidance (meters)

vesc_twist_node:
  ros__parameters:
    max_potential_rpm : 20000
    steering_polarity : 1
    throttle_polarity : 1
    zero_throttle : -0.03200000000000003
    max_throttle : 0.382
    min_throttle : 0.363
    max_right_steering : 0.792
    straight_steering : -0.21999999999999997
    max_left_steering : -0.831

adafruit_twist_node:
  ros__parameters:
    steering_polarity : 1
    throttle_polarity : 1
    zero_throttle : -0.03200000000000003
    max_throttle : 0.382
    min_throttle : 0.363
    max_right_steering : 0.792
    straight_steering : -0.21999999999999997
    max_left_steering : -0.831